config/routes.rb
FavouriteTweets::Application.routes.draw do
  resources :synchronizations

  resources :tweets do
    collection do
      get :get_recent
    end
  end

  root to: 'tweets#index'

end

app/models/media.rb
class Media < ActiveRecord::Base
  belongs_to :tweet
end

app/models/synchronization.rb
class Synchronization < ActiveRecord::Base
  scope :success, -> { where(is_success: true) }

  attr_accessor :run_at

  def self.is_allowed
    !success.where(arel_table[:created_at].gt(1.minute.ago)).any?
  end
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  has_many :medias

  validates :tweet_id, :message, :tweet_user_name, :tweet_user_screen_name, :lang, presence: true
  validates :tweet_id, uniqueness: true


  def self.get_recent_tweets
    twitter_messages = Twitter::Client.get_recent_tweets
    twitter_messages.each do |twitter_message|
      next if Tweet.find_by(tweet_id: twitter_message.id)

      tweet = Tweet.create(
          tweet_id: twitter_message.id,
          message: twitter_message.full_text,
          tweet_user_name: twitter_message.user.name,
          tweet_user_screen_name: twitter_message.user.screen_name,
          tweet_user_profile_image_url: twitter_message.user.profile_image_url.to_s,
          lang: twitter_message.lang
      )

      twitter_message.media.each do |twitter_message_media|
        tweet.medias.create(
            media_type: twitter_message_media.class.to_s,
            media_url: twitter_message_media.url.to_s
        )
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/synchronizations_controller.rb
class SynchronizationsController < ApplicationController
  before_action :set_synchronization, only: [:show, :destroy]

  # GET /synchronizations
  def index
    @synchronizations = Resque.all_schedules || {}
  end

  # GET /synchronizations/new
  def new
    @synchronization = Synchronization.new
  end

  # GET /synchronizations/1/edit
  def edit
  end

  # POST /synchronizations
  def create
    run_at = Whenever::Output::Cron.new(1.day, nil, synchronization_params['run_at']).time_in_cron_syntax

    if run_at.present?
      Resque.set_schedule(
          SecureRandom.uuid,
          {class: 'Tweet',
           cron: run_at,
           queue: 'tweets',
           args: 'get_recent_tweets',
           persist: true
          }
      )
      redirect_to synchronizations_url, notice: 'Synchronization was successfully created.'
    else
      render action: 'new'
    end
  end

  # DELETE /synchronizations/1
  def destroy
    Resque.remove_schedule(params[:id])
    redirect_to synchronizations_url, notice: 'Synchronization was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_synchronization
    @synchronization = Resque.fetch_schedule(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def synchronization_params
    params[:synchronization]
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_action :set_langs, only: [:index]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.order(created_at: :desc)

    if params[:langs].present?
      @tweets = @tweets.where(lang: params[:langs])
    end

    @tweets = @tweets.paginate(page: params[:page], per_page: 10)
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  # def update
  #   if @tweet.update(tweet_params)
  #     redirect_to @tweet, notice: 'Tweet was successfully updated.'
  #   else
  #     render action: 'edit'
  #   end
  # end

# DELETE /tweets/1
# DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    redirect_to tweets_url
  end

  def get_recent
    Tweet.get_recent_tweets
    redirect_to tweets_url
  end

  private
# Use callbacks to share common setup or constraints between actions.
  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def set_langs
    @langs = Tweet.pluck(:lang).uniq.sort
  end

# Never trust parameters from the scary internet, only allow the white list through.
#   def tweet_params
#     params.require(:tweet).permit(:message)
#   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/synchronizations_helper.rb
module SynchronizationsHelper
  def synchronization_time(synchronization)
    time = Cron2English.parse(synchronization['cron'])
   time[1].humanize + ' at ' + time[0]
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def message(tweet)
    #TODO Add some formatting
    tweet.message
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FavouriteTweets</title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to 'Tweets', tweets_path %></li>
          <li><%= link_to "Settings", synchronizations_path %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/synchronizations/_form.html.erb
<%= form_for(@synchronization) do |f| %>
    <% if @synchronization.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@synchronization.errors.count, "error") %> prohibited this synchronization from being
            saved:</h2>

          <ul>
            <% @synchronization.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="actions">
      Get new tweets at: </br>
      <%= f.text_field :run_at, id: 'timepicker' %> <br/>
      <%= f.submit 'Create', class: 'btn btn-info' %>
      <%= link_to 'Reset', synchronizations_path, class: 'btn btn-danger' %>
    </div>
<% end %>

app/views/synchronizations/index.html.erb
<div class="page-header">
  <h1>Settings</h1>
  <%= link_to 'Create new Synchronization', new_synchronization_path, class: 'btn btn-info' %>
</div>

<table class="table table-striped">
  <thead>
  <tr>
    <th width="90%"></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @synchronizations.each_pair do |synchronization_name, synchronization_params| %>
      <tr>
        <td><%= synchronization_time(synchronization_params) %></td>
        <td>
          <%= link_to 'Destroy', '/synchronizations/' + synchronization_name,
                      method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger' %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/synchronizations/new.html.erb
<div class="page-header">
  <h1>New synchronization</h1>
</div>

<%= render 'form' %>

app/views/tweets/index.html.erb
<div class="page-header">
  <h1>Tweets</h1>
  <%= link_to 'Get new Tweets', get_recent_tweets_path,
              class: 'btn btn-info' %>
  <hr />
  <%= form_tag tweets_path(@user), method: 'get', class: 'lang-select' do -%>
      <%= select_tag :langs, options_for_select(@langs.each { |l| [l, l] }, params[:langs]),
                     {multiple: true} %>
      <%= submit_tag 'Search', class: 'btn btn-info'%>
  <% end -%>
</div>

<table class="table table-striped">
  <thead>
  <tr>
    <th width="85%">Tweet</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @tweets.each do |tweet| %>
      <tr>
        <td><%= message(tweet) %></td>
        <td>
          <%= link_to t('.show', default: t("helpers.links.show")), tweet_path(tweet),
                      class: 'btn btn-info' %>
          <%= link_to t('.destroy', default: t("helpers.links.destroy")),
                      tweet_path(tweet), method: :delete, class: 'btn btn-danger' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= will_paginate @tweets %>

app/views/tweets/show.html.erb
<%- model_class = Tweet -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:tweet_id) %>:</strong></dt>
  <dd><%= @tweet.tweet_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tweet_user_name) %>:</strong></dt>
  <dd><%= @tweet.tweet_user_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tweet_user_screen_name) %>:</strong></dt>
  <dd><%= @tweet.tweet_user_screen_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tweet_user_profile_image_url) %>:</strong></dt>
  <dd><%= @tweet.tweet_user_profile_image_url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:message) %>:</strong></dt>
  <dd><%= @tweet.message %></dd>
  <dt><strong><%= model_class.human_attribute_name(:lang) %>:</strong></dt>
  <dd><%= @tweet.lang %></dd>
  <dt><strong><%= model_class.human_attribute_name(:is_viewed) %>:</strong></dt>
  <dd><%= @tweet.is_viewed %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              tweets_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_tweet_path(@tweet), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              tweet_path(@tweet),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>